name: Create new ISO

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Create new ISO
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get install -y live-build imagemagick
          
      - name: Install debian live-build
        run: |
          curl "https://ftp.debian.org/debian/pool/main/l/live-build/live-build_20230502_all.deb" > live-build.deb
          sudo dpkg -i live-build.deb
          curl "https://ftp.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2023.3_all.deb" > keyring.deb
          sudo dpkg -i keyring.deb
          
      - name: Configure imagemagick
        run: |
          sudo rm /etc/ImageMagick-6/policy.xml
        
      - name: Build ISO
        run: |
          sudo bash build_image.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./image_root/live-image-amd64.hybrid.iso
          asset_name: live-image-amd64.iso
          asset_content_type: application/octetstream
